global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'go-app'
    static_configs:
      - targets: ['go-app:2112'] 

# Uncomment to configure the remote endpoint
# remote_write:
#   - url:
#     basic_auth:
#       username:
#       password_file: /run/secrets/remote-write-password 

